/*
 * File: app/view/Lagerfach.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('BergInventur.view.Lagerfach', {
    extend: 'Ext.Container',
    alias: 'widget.lagerfach',

    config: {
        itemId: 'lagerfachdetail_id',
        items: [
            {
                xtype: 'titlebar',
                docked: 'top',
                itemId: 'titlebar_id',
                title: 'Test'
            },
            {
                xtype: 'toolbar',
                docked: 'top',
                itemId: 'griddetaillagerfach_titlebar',
                items: [
                    {
                        xtype: 'button',
                        itemId: 'griddetailbackbtlagerfach',
                        maxHeight: 80,
                        maxWidth: 80,
                        ui: 'back',
                        text: 'zurück'
                    },
                    {
                        xtype: 'spacer',
                        ui: 'light'
                    },
                    {
                        xtype: 'button',
                        itemId: 'speichern_anzahl',
                        maxHeight: 80,
                        ui: 'confirm',
                        text: 'speichern'
                    }
                ]
            },
            {
                xtype: 'fieldset',
                itemId: 'griddetailfieldsetlagerfach',
                items: [
                    {
                        xtype: 'textfield',
                        label: 'Field',
                        labelWidth: '40%'
                    }
                ]
            },
            {
                xtype: 'fieldset',
                itemId: 'griddetailfieldsetlagerfach1',
                items: [
                    {
                        xtype: 'numberfield',
                        itemId: 'gezaehlt',
                        label: 'Field'
                    }
                ]
            }
        ]
    }

});