/*
 * File: app/view/Login.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('BergInventur.view.Login', {
    extend: 'Ext.form.Panel',
    alias: 'widget.loginview',

    config: {
        ui: 'light',
        scrollable: false,
        items: [
            {
                xtype: 'image',
                itemId: 'BildmitSchluessel',
                style: 'width:80px;height:80px;margin:auto;top:35px',
                src: 'resources/images/74sgetdtestra3251gffcbgcAS.png'
            },
            {
                xtype: 'fieldset',
                title: 'Berg Inventur V 2.7',
                items: [
                    {
                        xtype: 'searchfield',
                        cls: 'mitarbeiter-suche',
                        itemId: 'mitarbeiter_suchen',
                        labelWidth: '0%',
                        placeHolder: 'bitte Ihren Namen eintragen'
                    },
                    {
                        xtype: 'fieldset',
                        hidden: true,
                        itemId: 'fieldset_mitarbeiter_suchen_liste',
                        ui: 'light',
                        scrollable: 'horizontal',
                        title: '',
                        items: [
                            {
                                xtype: 'list',
                                docked: 'bottom',
                                height: 0,
                                hidden: false,
                                itemId: 'mitarbeiter_suchen_liste',
                                ui: 'dark',
                                itemTpl: [
                                    '<p class="mitarbeiter-item">{Name}</p>'
                                ],
                                infinite: true
                            }
                        ]
                    },
                    {
                        xtype: 'textfield',
                        hidden: true,
                        itemId: 'userNameTextField',
                        name: 'userNameTextField',
                        required: true,
                        value: [
                            //    'Jörg Foerster'
                        ],
                        placeHolder: 'Vorname Nachname'
                    },
                    {
                        xtype: 'selectfield',
                        itemId: 'lagernrSelectField',
                        label: 'Standort',
                        options: [
                            {
                                text: 'Stendal',
                                value: '10'
                            },
                            {
                                text: 'Dessau',
                                value: '20'
                            },
                            {
                                text: 'Brandenburg',
                                value: '30'
                            },
                            {
                                text: 'Magdeburg',
                                value: '40'
                            },
                            {
                                text: 'Perleberg',
                                value: '50'
                            },
                            {
                                text: 'Wildau',
                                value: '60'
                            },
                            {
                                text: 'Lindenberg',
                                value: '70'
                            },
                            {
                                text: 'Potsdam',
                                value: '80'
                            },
                            {
                                text: 'Fürstenwalde',
                                value: '90'
                            }
                        ],
                        usePicker: false
                    }
                ]
            },
            {
                xtype: 'button',
                itemId: 'logInButton',
                margin: '15px',
                text: 'Anmelden'
            }
        ],
        listeners: [
            {
                fn: 'onLogInButtonTap',
                event: 'tap',
                delegate: '#logInButton'
            }
        ]
    },

    onLogInButtonTap: function(button, e, eOpts) {

        var me = this,
            usernameField = me.down('#mitarbeiter_suchen'),

            username = usernameField.getValue(),
            lagernrField=me.down('#lagernrSelectField'),
            lagernr = lagernrField.getValue()    ;


        //Filter auf den Namen, damit für die Statistik ein valider Name vorhanden ist

        Ext.getStore('Store_LagerMitarbeiterLogistic').filterBy(function(record){

            var Mitarbeiter = record.get('Name');
            if(Mitarbeiter == username)
            {


                return record;

            }});

            if (Ext.getStore('Store_LagerMitarbeiterLogistic').getCount() > 0 )
            { 
                me.fireEvent('signInCommand', me, username,lagernr);
            }
            else Ext.Msg.alert('Fehler', 'Der Name '+username+' ist nicht in der Datenbank enthalten', Ext.emptyFn);

    }

});