/*
 * File: app/view/Search_Container.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('BergInventur.view.Search_Container', {
    extend: 'Ext.Container',
    alias: 'widget.searchcontainer',

    config: {
        itemId: 'searchcontainer',
        items: [
            {
                xtype: 'toolbar',
                docked: 'top',
                itemId: 'id_toolbar',
                ui: 'light',
                title: 'Inventur in Lagernr:',
                listeners: [
                    {
                        fn: function(element, eOpts) {

                            var me = this,
                                standort_string='';

                            //console.log(element);
                            //console.log(me);
                            //console.log(me._title._html);

                            switch (LagerInventur.standort)
                            {
                                case '10':
                                standort_string='Inventur im Lager: Stendal';
                                break;
                                case '20':
                                standort_string='Inventur im Lager: Dessau';
                                break;
                                case '30':
                                standort_string='Inventur im Lager: Brandenburg';
                                break;
                                case '40':
                                standort_string='Inventur im Lager: Magdeburg';
                                break;
                                case '50':
                                standort_string='Inventur im Lager: Perleberg';
                                break;
                                default:
                                standort_string='Kein Lager gewählt';
                            }  




                            me._title.setHtml(standort_string);



                        },
                        event: 'painted'
                    }
                ]
            },
            {
                xtype: 'label',
                centered: false,
                itemId: 'signInFailedLabel',
                margin: '15px',
                style: 'color:#990000;margin:15px 10px;',
                ui: ''
            },
            {
                xtype: 'formpanel',
                itemId: 'myformpanel',
                layout: {
                    type: 'fit'
                },
                items: [
                    {
                        xtype: 'toolbar',
                        docked: 'top',
                        height: 40,
                        itemId: 'suchetoolbar1',
                        ui: 'searchbar',
                        width: '100%',
                        items: [
                            {
                                xtype: 'spacer',
                                ui: 'searchbar',
                                width: 5
                            },
                            {
                                xtype: 'checkboxfield',
                                flex: 9,
                                id: 'id_artsuche',
                                itemId: 'mycheckbox',
                                clearIcon: false,
                                label: 'Lagerfach des Artikels suchen?',
                                labelWidth: '90%',
                                name: 'ArtSuche'
                            },
                            {
                                xtype: 'spacer',
                                height: 23,
                                width: 200
                            }
                        ]
                    },
                    {
                        xtype: 'toolbar',
                        docked: 'top',
                        id: 'id_suchetoolbar',
                        itemId: 'suchetoolbar',
                        ui: 'searchbar',
                        width: '100%',
                        items: [
                            {
                                xtype: 'spacer',
                                width: 5
                            },
                            {
                                xtype: 'searchfield',
                                id: 'lagerfachField',
                                width: '80%',
                                name: 'LagerfachField',
                                required: true,
                                value: [
                                    // 'E2813-9-0'
                                ],
                                placeHolder: 'Lagerfach min 6 Zeichen eingeben!'
                            },
                            {
                                xtype: 'button',
                                itemId: 'suchen_lagernr',
                                ui: 'action',
                                width: '10%',
                                text: 'Suchen'
                            },
                            {
                                xtype: 'spacer',
                                height: 23,
                                width: 10
                            }
                        ]
                    },
                    {
                        xtype: 'fieldset',
                        docked: 'top',
                        itemId: 'fieldset_lagerfach',
                        ui: 'dark',
                        layout: {
                            type: 'fit'
                        },
                        scrollable: 'horizontal',
                        title: '',
                        items: [
                            {
                                xtype: 'dataview',
                                docked: 'bottom',
                                height: 470,
                                itemId: 'fachlagerlist',
                                ui: 'dark',
                                scrollable: 'vertical',
                                emptyText: 'es wurden keine Artikel gefunden',
                                itemTpl: [
                                    '',
                                    '<table style="width: 100% ;height: 30px"; border="1" frame="below" rules="none" >',
                                    '<tbody>',
                                    '<tr>',
                                    '<tpl>',
                                    '     <td style="width: 15% !important;text-align: left;">{art_herst_art_nr} </td>',
                                    '     <td style="width: 10% !important;text-align: left;color: #ff0000;">{fachnummer} </td>',
                                    '     <td style="width: 15% !important;text-align: left;">{art_text1}</td> ',
                                    '    <td style="width: 10% !important;text-align: right;color: #0c00ff;">{info}</td>',
                                    '</tpl> ',
                                    '</tr>',
                                    '</tbody>',
                                    '</table>'
                                ],
                                loadingText: 'Suche jetzt die Artikel',
                                store: 'Store_Artikelnummern'
                            }
                        ]
                    }
                ]
            }
        ],
        listeners: [
            {
                fn: 'onMycheckboxCheck',
                event: 'check',
                delegate: '#id_artsuche'
            },
            {
                fn: 'onId_artsucheUncheck',
                event: 'uncheck',
                delegate: '#id_artsuche'
            },
            {
                fn: 'onSuchen_lagerfachTap',
                event: 'tap',
                delegate: '#suchen_lagernr'
            }
        ]
    },

    onMycheckboxCheck: function(checkboxfield, e, eOpts) {
        Ext.getCmp('lagerfachField').setPlaceHolder('Hersteller-Nr. oder EAN eingeben, das Lagerfach wird ermittelt! Min 4 Zeichen eingeben!');

        Ext.getCmp('id_artsuche').setValue(true);
        /*

        var me = this,
        PlaceHolder = me.down('#lagerfachField'),
        M_PlaceHolder = PlaceHolder.getPlaceHolder();
        console.log(me.down('#id_artsuche')._checked);
        console.log(checkboxfield);

        if ( me.down('#id_artsuche').getValue() === 'true' )
        {
        me.down('#lagerfachField').setPlaceHolder('Hersteller-Nr. oder EAN eingeben, das Lagerfach wird ermittelt!');
        //Ext.Msg.alert('Fehler', 'Der Name darf nicht leer sein', Ext.emptyFn);
    }
    else
    {
        me.down('#lagerfachField').setPlaceHolder('Lagerfach min 6 Zeichen eingeben!');

    }

    console.log(me.down('#id_artsuche').getValue());

    Ext.getCmp('lagerfachField').setPlaceHolder('Hersteller-Nr. oder EAN eingeben, das Lagerfach wird ermittelt!');
    */
    },

    onId_artsucheUncheck: function(checkboxfield, e, eOpts) {
        Ext.getCmp('lagerfachField').setPlaceHolder('Lagerfach min 6 Zeichen eingeben!');
        Ext.getCmp('id_artsuche').setValue(false);
    },

    onSuchen_lagerfachTap: function(button, e, eOpts) {
        var me = this,
            m_searchfield_lagernr = me.down('#lagerfachField'),
            label = me.down('#signInFailedLabel'),
            m_artikelsuche=Ext.getCmp('id_artsuche').getValue(),
            m_lagernr = m_searchfield_lagernr.getValue();



        //console.log('LagerNr. Suchen Tap');
        //console.log(Ext.getCmp('id_artsuche').getValue());
        Ext.getStore('Store_Artikelnummern').clearData();

        //task.delay(500);
        me.fireEvent('fn_search_lagernr', me, m_lagernr,m_artikelsuche);

    }

});