/*
 * File: app/model/auftragsnummern.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('BergInventur.model.auftragsnummern', {
    extend: 'Ext.data.Model',
    alias: 'model.auftragsnummern',

    config: {
        proxy: {
            type: 'ajax',
            api: {
                create: 'resources/services/get_artikelnummern.php?action=create',
                read: 'resources/services/get_artikelnummern.php?action=ListeArtikelnummern',
                update: 'resources/services/get_artikelnummern.php?action=update',
                destroy: 'resources/services/get_artikelnummern.php?action='
            },
            extraParams: {
                keyword: '',
                standort: ''
            },
            reader: {
                type: 'json',
                rootProperty: 'artikel'
            },
            writer: {
                type: 'json'
            }
        },
        fields: [
            {
                name: 'fachnummer'
            },
            {
                name: 'carlanr'
            },
            {
                name: 'art_herst_art_nr'
            },
            {
                name: 'art_text1'
            },
            {
                name: 'menge'
            },
            {
                name: 'me_we'
            },
            {
                name: 'gezaehlt'
            },
            {
                name: 'wurde_gezaehlt'
            },
            {
                name: 'gezaehlt_am'
            },
            {
                name: 'zaehler'
            },
            {
                name: 'info'
            },
            {
                name: 'lagerort'
            },
            {
                name: 'ze'
            },
            {
                name: 'Activity_Type'
            },
            {
                name: 'gew_lieferdatum'
            }
        ]
    }
});