/*
 * File: app/model/Model_LagerMitarbeiterLogistic.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('BergInventur.model.Model_LagerMitarbeiterLogistic', {
    extend: 'Ext.data.Model',

    config: {
        proxy: {
            type: 'ajax',
            api: {
                create: 'resources/services/get_login.php?action=create',
                read: 'resources/services/get_login.php?action=Liste',
                update: 'resources/services/get_login.php?action=update',
                destroy: 'resources/services/get_login.php?action='
            },
            extraParams: {
                keyword: '',
                standort: ''
            },
            reader: {
                type: 'json',
                rootProperty: 'akiv'
            },
            writer: {
                type: 'json'
            }
        },
        fields: [
            {
                name: 'Code'
            },
            {
                name: 'Name'
            },
            {
                name: 'PickBatchIdentifierId'
            },
            {
                name: 'suchcode'
            }
        ]
    }
});