/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

//@require @packageOverrides
Ext.Loader.setConfig({

});

Ext.application({
    models: [
        'Model_ActivityLine',
        'Model_LagerMitarbeiterLogistic'
    ],
    stores: [
        'artikelnummern',
        'activityline',
        'Store_LagerMitarbeiterLogistic'
    ],
    views: [
        'Search_Container',
        'Login'
    ],
    requires: [
        'Ext.MessageBox',
        'Ext.Img',
        'Ext.form.FieldSet',
        'Ext.field.Select',
        'Ext.Label',
        'Ext.field.Search',
        'Ext.plugin.PullRefresh'
    ],
    controllers: [
        'Search_Controller',
        'LoginController'
    ],
    icon: {
        '57': 'resources/icons/Icon_.png',
        // Non-Retina iPhone, iPod touch, and Android devices
        '72': 'resources/icons/Icon~ipad.png',
        // Non-Retina iPad
        '114': 'resources/icons/Icon@2x.png',
        // iPhone 5 and iPod touch (fifth generation)
        '144': 'resources/icons/Icon~ipad@2x.png'// Retina iPad
    },
    isIconPrecomposed: true,
    name: 'BergInventur',
    startupImage: {
        '320x460': 'resources/startup/Default.jpg',
        // Non-retina iPhone, iPod touch, and all Android devices
        '640x920': 'resources/startup/640x920.png',
        // Retina iPhone and iPod touch
        '640x1096': 'resources/startup/640x1096.png',
        // iPhone 5 and iPod touch (fifth generation)
        '768x1004': 'resources/startup/768x1004.png',
        //  Non-retina iPad (first and second generation) in portrait orientation
        '748x1024': 'resources/startup/748x1024.png',
        //  Non-retina iPad (first and second generation) in landscape orientation
        '1536x2008': 'resources/startup/1536x2008.png',
        // : Retina iPad (third generation) in portrait orientation
        '1496x2048': 'resources/startup/1496x2048.png'// : Retina iPad (third generation) in landscape orientation
    },

    onUpdated: function() {
        Ext.Msg.confirm(
        "Software Update",
        "Die Software wurde durch den Entwickler erfolgreich aktualisiert! Möchten Sie die App neu laden?",
        function(buttonId) {
            if (buttonId === 'yes') {
                window.location.reload();
            }
        },
        this
        );
    },

    launch: function() {
        Ext.Viewport.add([
        {xtype: 'loginview' }

        ]
        );
        Ext.create('BergInventur.view.Search_Container', {fullscreen: true});
    }

});
