/*
 * File: app/controller/LoginController.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('BergInventur.controller.LoginController', {
    extend: 'Ext.app.Controller',

    config: {
        refs: {
            mitarbeitersuche: 'loginview #mitarbeiter_suchen_liste',
            searchContainer: 'startContainer',
            loginView: {
                autoCreate: true,
                selector: 'loginview',
                xtype: 'loginview'
            }
        },

        control: {
            "loginView": {
                signInCommand: 'onSignInCommand'
            },
            "mitarbeitersuche": {
                itemsingletap: 'onMitarbeiter_suchen_List'
            },
            "searchfield#mitarbeiter_suchen": {
                keyup: 'onMitarbeiter_Suchen_Keyup'
            }
        }
    },

    onSignInCommand: function(view, username, lagernr) {

        var me = this,
            loginView = me.getLoginView();
        LagerInventur.username=username;
        LagerInventur.standort=lagernr;

        console.log('LoginView zerstört');
        console.log(username);
        console.log(lagernr);

        function ping(){
            Ext.Ajax.request({

                url: 'resources/services/leer.html',
                method: 'get',
                success: function(response){
                    // alert('reply');
                    //  console.log('ping ok');

                },     
                failure: function(response){
                    //  alert('VPN Verbindung unterbrochen');
                    Ext.Msg.alert('Fehler','Verbindung zum Server verloren');
                }
            });
        }

        var pingTimer;

        function startPing() {
            pingTimer = setInterval(function () {
                ping();
                //  console.log('ping');
                // $scroll.trigger('next');
            }, 5000); //alle 5 Sekunden
        }

        // start to automatically cycle slides
        startPing();

        // set next/previous buttons as clearInterval triggers 
        //var $stopTriggers = $('img.right').add('img.left'); // left right

        // function to stop auto-ping
        function stopPing() {
            clearInterval(pingTimer);
            setTimeout(startPing, 5000); // restart after 5 seconds
        }

        Ext.Viewport.remove(Ext.Viewport.getActiveItem(), true);

        //Ext.Viewport.add([{xtype: 'startContainer'}]);

        //console.log('startContainer add erledigt');
    },

    onMitarbeiter_suchen_List: function(dataview, index, target, record, e, eOpts) {
        this.getLoginView().down("#mitarbeiter_suchen").setValue(record.data.Name);
        this.getLoginView().down('#mitarbeiter_suchen_liste').setMinHeight(0);
        this.getLoginView().down('#mitarbeiter_suchen_liste').setHeight(0);
        this.getLoginView().down('#fieldset_mitarbeiter_suchen_liste').hide();
        //this.getLoginView().down('#mitarbeiter_suchen').reset();
    },

    onMitarbeiter_Suchen_Keyup: function(textfield, e, eOpts) {
        console.log('LagerMitarbeiterLogistic keyup');

        var me = this,
            SucheField = this.getLoginView().down('#mitarbeiter_suchen'),
            Suche = SucheField.getValue().toLowerCase(),
            store = Ext.getStore("Store_LagerMitarbeiterLogistic");



        //setzt das scrollen auf dem Form auf disable
        this.getLoginView().getScrollable().getScroller().setDisabled(true);

        //Store load dauert zu lange und es werden zuviele  Daten bewegt  
        //store.getProxy()._extraParams.keyword = Suche;
        //store.loadPage(1);

        // Filter ist schneller load wird am Anfang bereits durchgeführt





        store.clearFilter();

        var filterSuche = [];
        filterSuche.push(new RegExp(Suche));

        store.filter('suchcode',filterSuche[0]);

        console.log(store.getCount());
        //this.getLoginview().down('#kunde_suchen_abbrechen').setBadgeText(store.getCount());
        var FieldSetSuche = this.getLoginView().down('#fieldset_mitarbeiter_suchen_liste'),
            SuchListe = this.getLoginView().down('#mitarbeiter_suchen_liste');

        //console.log(SuchListe);
        if (store.getCount() > 0) {
            FieldSetSuche.setHidden(false);
            SuchListe.setHidden(false);
            SuchListe.setLoadingText('Lade Kunden');
            SuchListe.setStore('Store_LagerMitarbeiterLogistic');
            SuchListe.setMaxHeight(210);
            SuchListe.setMinHeight(35);
            SuchListe.setHeight(35 * store.getCount());

        }
        else{

            SuchListe.setHeight(0);
            SuchListe.setMinHeight(0);
            SuchListe.setHidden(true);
            FieldSetSuche.setHidden(true);

        }
    },

    slideLeftTransition: function() {
        return { type: 'slide', direction: 'left' };
    },

    activeMain: function() {
        console.log('Main');

        Ext.Viewport.animateActiveItem(this.getSearchContainer(), this.slideLeftTransition);

    }

});