/*
 * File: app/controller/Search_Controller.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('BergInventur.controller.Search_Controller', {
    extend: 'Ext.app.Controller',

    config: {
        models: [
            'auftragsnummern'
        ],
        stores: [
            'artikelnummern'
        ],
        views: [
            'Search_Container',
            'Lagerfach'
        ],

        refs: {
            SearchContainer: {
                autoCreate: true,
                selector: 'searchcontainer',
                xtype: 'searchcontainer'
            },
            lagerfach: {
                autoCreate: true,
                selector: 'lagerfach',
                xtype: 'lagerfach'
            }
        },

        control: {
            "SearchContainer": {
                fn_search_lagernr: 'on_fn_search_lagerfach',
                showSignInFailedMessage: 'showSignInFailedMessage'
            },
            "button#griddetailbackbtlagerfach": {
                tap: 'onButtonTap'
            },
            "button#speichern_anzahl": {
                tap: 'onButtonSpreichern'
            },
            "dataview#fachlagerlist": {
                itemtaphold: 'onDataviewItemTaphold',
                itemtap: 'onDataviewItemTap'
            }
        }
    },

    on_fn_search_lagerfach: function(container, m_searchfield_lagernr, m_artikelsuche) {
        var me = this,
            m_Search_Container = me.getSearchContainer();
        console.log(m_searchfield_lagernr);
        console.log(m_artikelsuche);

        if (m_artikelsuche !== true)
        {
            var suchfeld = m_searchfield_lagernr.replace(/-/g,'');
            if (suchfeld.length <  6 ) {
                this.showSignInFailedMessage('Bitte mindestens 6 Zeichen eingeben. (' + suchfeld.length +')');
                return;
            }

            this.showSignInFailedMessage('');


            var store_artsta = Ext.getStore('Store_Artikelnummern');
            console.log(store_artsta);

            store_artsta.getProxy()._extraParams.keyword = m_searchfield_lagernr;
            store_artsta.getProxy()._extraParams.standort = LagerInventur.standort;
            store_artsta.getProxy()._extraParams.artikelsuche = 'false';
            store_artsta.load();
        }
        else
        {
            var suchfeldL = m_searchfield_lagernr.replace(/-/g,'');
            if (suchfeldL.length <  4 ) {
                this.showSignInFailedMessage('Bitte mindestens 4 Zeichen eingeben. (' + suchfeldL.length +')');
                return;
            }

            this.showSignInFailedMessage('');

            // Ext.Msg.alert('Fehler', 'Artikelsuche', Ext.emptyFn); 
            var store_artstasuche = Ext.getStore('Store_Artikelnummern');
            console.log(store_artstasuche);
            store_artstasuche.getProxy()._extraParams.keyword = m_searchfield_lagernr;
            store_artstasuche.getProxy()._extraParams.standort = LagerInventur.standort;
            store_artstasuche.getProxy()._extraParams.artikelsuche = m_artikelsuche;
            store_artstasuche.load();
        }

    },

    onButtonTap: function(button, e, eOpts) {
        this.onZurueck(  button, e);
    },

    onButtonSpreichern: function(button, e, eOpts) {
        this.onSpeichern(  button, e);
    },

    showSignInFailedMessage: function(message) {
        var searchContainer = this.getSearchContainer(),
            label = searchContainer.down('#signInFailedLabel');

        label.setHtml(message);
        console.log(message);

        label.show();
    },

    onDataviewItemTaphold: function(dataview, index, target, record, e, eOpts) {
        this.onDataView_tap_hold(record, target, index);
    },

    onDataviewItemTap: function(dataview, index, target, record, e, eOpts) {
        // console.log('ttt');
        this.onDataView_tap_hold(record, target, index);
    },

    onSpeichern: function(button, e, eOtps) {

        var currentDaten = this.getLagerfach().getRecord(),
            newValue = this.getLagerfach().down("#gezaehlt")._value,
            now = new Date(),
            me = this;

        // function speichern -------------------------------------------------------------------------------

        var schreibe = function (){
            currentDaten.setConfig({
                fields:[
                {name:'carlanr', type:'string'},    
                {name:'menge_im_fach', type:'string'},   
                {name:'gezaehlt', type:'string'},    
                {name:'zaehler', type:'string'},  
                //  {name:'lager', type:'string'},            
                {name:'fachnummer', type:'string'},    
                {name:'art_text1', type:'string'},  
                {name:'art_herst_art_nr', type:'string'}, 
                {name:'lagerort', type:'string'},  
                {name:'me_we', type:'string'},   
                {name:'ze', type:'string'},             
                {name:'gezaehlt_am', type:'date',dateFormat: 'c'

                }        
            ]});

            currentDaten.set('ze',currentDaten.data.ze);
            currentDaten.set('carlanr',currentDaten.data.carlanr);
            currentDaten.set('menge_im_fach',currentDaten.data.menge);
            currentDaten.set('fachnummer',currentDaten.data.fachnummer);
            currentDaten.set('art_text1',currentDaten.data.art_text1);
            currentDaten.set('art_herst_art_nr',currentDaten.data.art_herst_art_nr);
            currentDaten.set('zaehler',LagerInventur.username);
            currentDaten.set('gezaehlt_am',now);
            currentDaten.set('me_we',currentDaten.data.me_we);
            currentDaten.set('gezaehlt',newValue);
            currentDaten.set('lagerort',currentDaten.data.lagerort);
            // 

            //  console.log(currentDaten.data.ze);

            var errors = currentDaten.validate();
            if (!errors.isValid()) {
                current.Daten.reject();

                //Ext.Msg.alert("Invalid", errors.getByField("content")[0].getMessage(), Ext.emptyFn);
                alert(errors.getByField("gezaehlt")[0].getMessage());
                return;
            }

            console.log(currentDaten.data.carlanr);

            // API in Modul schreiben, damit CURD aufgerufen werden kann 
            // currentDaten.setProxy(Ext.getStore("Store_Artikelnummern").getProxy());

            //ruft create auf weil phantom auf true gesetzt bei false update
            Ext.getStore("Store_Artikelnummern").add(currentDaten); 
            //  currentDaten.phantom= false;

            //   console.log(currentDaten.save);

            currentDaten.save( {

                success: function(record,option){
                    console.log('ok');
                    Ext.Msg.alert('Katalogartikel-Nr. '+ currentDaten.data.carlanr,'Menge '+ newValue+' wurden eingetragen\n',  Ext.emptyFn);
                    currentDaten.commit(); // removes the dirty marker
                    me.onZurueck(button,e);
                    Ext.getStore('Store_Artikelnummern').load();
                },
                failure: function(response){
                    console.log('fehler');
                    Ext.Msg.alert('Katalogartikel-Nr. '+ currentDaten.data.carlanr,'Fehler beim Speichern\n',  Ext.emptyFn);
                    currentDaten.reject();
                },
                scope:this
            });

        };

        // Ende Speichern ------------------------------------------------------------------------

        console.log (newValue);

        if ( newValue==='') 
        {	Ext.Msg.alert('Fehler','gezählt darf nicht leer sein',Ext.emptyFn);}

        else  {

            if ( Number(newValue) != Number(currentDaten.data.menge))
            {
                Ext.Msg.show({
                    title: 'Abweichungen in der Menge ',
                    message:  LagerInventur.username + ", "+
                    "das Ergebnis stimmt nicht mit dem Bestand der NAV überein." +
                    "Möchten Sie trotzdem den gezählten Bestand speichern?",
                    width: 300,
                    buttons: [ {
                        itemId : 'yes',
                        text: 'Ja'
                        //ui: 'action'
                    },
                    {
                        itemId : 'no',
                        text: 'noch einmal zählen',
                    ui: 'action'}             
                    ],
                    promt:{
                        maxlength : 180,
                    autocapitalize : false },
                    fn : function(text,btn, itemId )             

                    {if(text == 'yes'){
                        schreibe(e,currentDaten,currentDaten,newValue,now);
                    }
                    else
                    {
                        console.log('nicht gespeichert! '+text+ btn);
                    }
                }});

            }

            else // wenn gezählt = Menge im Lagerfach 
            {
                schreibe(e,currentDaten,newValue,now);
            }
        }
    },

    onZurueck: function(button, e) {

        Ext.Viewport.animateActiveItem(this.getSearchContainer(), this.slideRightTransition); 
    },

    activateLagerfach: function() {
        // Ext.Viewport.animateActiveItem(this.getLagerfach(), this.slideRightTransition);
        Ext.Viewport.setActiveItem(this.getLagerfach());

    },

    slideRightTransition: function() {
        return {
            type: 'slide', 
            direction: 'right', 
            duration: 400
        };
    },

    onDataView_tap_hold: function(record, index, target) {
        var newcont = this.getLagerfach();
        newcont.setRecord(record);

        console.log('Arikelsiuche');
        console.log(Ext.getCmp('id_artsuche').getValue());
        //console.log(record.data.Activity_Type);
        //console.log(record.data.gew_lieferdatum);
        if (Ext.getCmp('id_artsuche').getValue() === true )
        {
            Ext.Msg.alert( 'Lagerplatzsuche', 'Bei der Lagerplatzsuche ist keine Erfassung der Bestände möglich');
        }
        else
        {

            if (record.data.Activity_Type !== null ) 
            {
                console.log('Bewegung');   
                var bewegung = record.data.Activity_Type;    
                if (bewegung===5)
                {bewegung='Kommissionierung';} 
                else {bewegung='Einlagerungen';} 
                Ext.Msg.alert('Eine Inventur z.Z. nicht möglich !!!', 'Am Lagerfach: ' + record.get('fachnummer')+ ' findet bis zum '+ record.data.gew_lieferdatum +' eine '+ bewegung + ' statt! ');
            }

            else
            { 


                console.log('keine Bewegung');


                if (newcont)
                {

                    //   var newTitel = newcont.down('#griddetailbackbtwerkstatt_titlebar');    
                    //   newTitel.setTitle('Kundenausstattung');

                    //  console.log(record);   

                    var newTitel = newcont.down('#titlebar_id');
                    newTitel.setTitle('Lagerfach '+ record.get('fachnummer'));
                    var fieldset0 = newcont.down('#griddetailfieldsetlagerfach');
                    var result = fieldset0.setConfig({ 
                        xtype: "fieldset",
                        id: "fieldset0",
                        title: "Angaben aus NAV",
                        instructions: 'Felder können nicht geändert werden.',
                        defaults: {
                            labelWidth: '25%',
                            xtype: "textfield"
                        },
                        items: [
                        { value: record.data.art_text1, name: "text1", label: "Text" , ClearIcon : false, readOnly: true, disabled: false, hidden: false},
                        { value: record.data.art_herst_art_nr, name: "art_herst_art_nr", label: "Hersteller-Art-Nr." , ClearIcon : false, readOnly: true, disabled: false},
                        { value: record.data.menge,name: "menge", label: "Menge" , ClearIcon : false, readOnly: true, disabled: false, hidden: true},
                        { value: record.data.menge,me_we: "me_we", label: "Menge WE" , ClearIcon : false, readOnly: true, disabled: false, hidden: true},  
                        { value: record.data.menge,ze: "ze", label: "ZE" , ClearIcon : false, readOnly: true, disabled: false, hidden: true},  
                        { value: record.data.menge,lagerort: "lagerort", label: "Lagerort" , ClearIcon : false, readOnly: true, disabled: false, hidden: true},              
                        { value: '????',name: "menge_anzeige", label: "Menge" , ClearIcon : false, readOnly: true, disabled: false}

                        //        { value: record.data.strnr,name: "strnr", label: "Strasse" , ClearIcon : false, readOnly: true, disabled: false},
                        //        { value: record.data.telefon, name: "telefon", label: "Telefon" , ClearIcon : false, readOnly: true, disabled: false},
                        //        { value: record.data.zbv3, name: "zbv3", label: "ATP plus & TKA" , ClearIcon : false, readOnly: true, disabled: false}

                        //	{ name: "categoryid", label: "Igendwas", xtype: "selectfield", store: "kunden_details_store", displayField: "name", valueField: "id" },

                        ]
                    });
                    var fieldset1 = newcont.down('#griddetailfieldsetlagerfach1');
                    var result1 = fieldset1.setConfig({ 
                        xtype: "fieldset",
                        id: "fieldset1",
                        title: "gezählte Menge",

                        defaults: {
                            labelWidth: '25%',
                            xtype: "numberfield"
                        },
                        items: [
                        {itemId:'gezaehlt',required: true, name: "gezaehlt", label: "gezaehlt" , ClearIcon : true, value:'' }


                        ]


                    });
                    // console.log(newcont.down("#gezaehlt")._value);

                }
                Ext.Viewport.animateActiveItem(newcont, this.slideRightTransition) ;   
            }
        }
    },

    init: function(application) {
        //globale Variablen
        LagerInventur={}; //erzeuge ich mir ein globales Objekt was dauerhaft besteht und dauerhaft erreichbar ist.
        LagerInventur.username='';
        LagerInventur.standort='';


        var code = 'de';

        if (code === 'de') { // in Deutsch übersetzen
            Ext.Date.monthNames = ["Januar", "Februar", "März", "April", "Mai", "Juni", "Juli", "August","September", "Oktober", "November", "Dezember"];
            Ext.Date.defaultFormat = 'd.m.Y';
            Ext.Date.getShortMonthName = function(month) {return Ext.Date.monthNames[month].substring(0, 3);};
            Ext.Date.monthNumbers = {
                Jan: 0,
                Feb: 1,
                "M\u00e4r": 2,
                Apr: 3,
                Mai: 4,
                Jun: 5,
                Jul: 6,
                Aug: 7,
                Sep: 8,
                Okt: 9,
                Nov: 10,
                Dez: 11
            };
            Ext.Date.getMonthNumber = function(name) {return Ext.Date.monthNumbers[name.substring(0, 1).toUpperCase() +name.substring(1, 3).toLowerCase()];};
            Ext.Date.dayNames = ["Sonntag", "Montag", "Dienstag", "Mittwoch", "Donnerstag", "Freitag","Samstag"];
            Ext.Date.getShortDayName = function(day) {return Ext.Date.dayNames[day].substring(0, 3);};
        }

    }

});